<a href="https://colab.research.google.com/github/Vishnum369/python-case-study/blob/main/Numpyassignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1)

In [ ]:
import numpy as np

arr = np.arange(10, 50)
reshaped_arr = arr.reshape((4, 10))
last_column = reshaped_arr[:, -1]
print("Reshaped matrix:\n", reshaped_arr)
print("Last column:\n", last_column)

Reshaped matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last column:
 [19 29 39 49]


2)

In [ ]:
import numpy as np
matrix_5s = np.full((3, 3), 5)
matrix_1to9 = np.arange(1, 10).reshape((3, 3))
sum_matrix = matrix_5s + matrix_1to9
elementwise_product = matrix_5s * matrix_1to9
transpose_result = elementwise_product.T

print("Matrix of 5s:\n", matrix_5s)
print("Matrix from 1 to 9:\n", matrix_1to9)
print("Sum of matrices:\n", sum_matrix)
print("Element-wise product:\n", elementwise_product)
print("Transpose of the product:\n", transpose_result)

Matrix of 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Matrix from 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of matrices:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Element-wise product:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose of the product:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


3)

In [ ]:
import numpy as np
arr = np.random.randint(10, 101, size=15)
print("Original array:\n", arr)
replaced_count = np.sum(arr > 50)
arr[arr > 50] = -1
print("\nModified array:\n", arr)
print("\nNumber of values replaced:", replaced_count)


Original array:
 [28 14 99 99 47 87 19 76 79 93 44 47 17 13 91]

Modified array:
 [28 14 -1 -1 47 -1 19 -1 -1 -1 44 47 17 13 -1]

Number of values replaced: 7


4)

In [ ]:
import numpy as np

arr = np.random.rand(5, 4)
print("Original array:\n", arr)

row_sums = np.sum(arr, axis=1)
max_row_index = np.argmax(row_sums)
print("\nRow with maximum sum (index {}):\n{}".format(max_row_index, arr[max_row_index]))

row_min = arr.min(axis=1, keepdims=True)
row_max = arr.max(axis=1, keepdims=True)
normalized_arr = (arr - row_min) / (row_max - row_min)

print("\nNormalized array:\n", normalized_arr)


Original array:
 [[0.27035353 0.89933167 0.24898772 0.14004714]
 [0.47137357 0.74069826 0.21828567 0.64557257]
 [0.78269171 0.20214117 0.55083017 0.64879947]
 [0.27621936 0.97517165 0.67565137 0.18139089]
 [0.91621879 0.94899469 0.25626485 0.18979567]]

Row with maximum sum (index 4):
[0.91621879 0.94899469 0.25626485 0.18979567]

Normalized array:
 [[0.17161734 1.         0.14347795 0.        ]
 [0.4844598  1.         0.         0.81791081]
 [1.         0.         0.60061781 0.76937022]
 [0.1194643  1.         0.62266623 0.        ]
 [0.95682832 1.         0.08755172 0.        ]]


5)

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(arr)
duplicates = np.array([item for item in unique_elements if np.count_nonzero(arr == item) > 1])
print("Unique elements:\n", unique_elements)
print("Duplicates:\n", duplicates)

Unique elements:
 [1 3 5 7 9]
Duplicates:
 [1 3 5]


6)

In [ ]:
import numpy as np
array_6x6 = np.arange(1, 37).reshape(6, 6)

submatrix_4x4 = array_6x6[1:5, 1:5]

even_numbers = submatrix_4x4[submatrix_4x4 % 2 == 0]

print("6×6 array:")
print(array_6x6)

print("\nMiddle 4×4 submatrix:")
print(submatrix_4x4)

print("\nEven numbers from the submatrix:")
print(even_numbers)


6×6 array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4×4 submatrix:
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers from the submatrix:
[ 8 10 14 16 20 22 26 28]


7)

In [ ]:
import numpy as np
array_3x4 = np.arange(12).reshape(3, 4)

array_2x6 = array_3x4.reshape(2, 6)

array_flat = array_2x6.flatten()

array_4x3 = array_flat.reshape(4, 3)

print("Original (3, 4) array:\n", array_3x4)
print("\nReshaped to (2, 6):\n", array_2x6)
print("\nFlattened 1D array:\n", array_flat)
print("\nReshaped back to (4, 3):\n", array_4x3)


Original (3, 4) array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2, 6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped back to (4, 3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8)

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
a_with_row = np.append(a, [[5, 6]], axis=0)

new_column = np.array([7, 8, 9]).reshape(-1, 1)
a_with_row_and_col = np.append(a_with_row, new_column, axis=1)

print("Original array:\n", a)
print("\nAfter appending row [5, 6]:\n", a_with_row)
print("\nAfter appending column [7, 8, 9]:\n", a_with_row_and_col)


Original array:
 [[1 2]
 [3 4]]

After appending row [5, 6]:
 [[1 2]
 [3 4]
 [5 6]]

After appending column [7, 8, 9]:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


9)

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate((a, b, c))
matrix_3x3 = joined.reshape(3, 3)
diagonal = np.diag(matrix_3x3)

print("Joined array:\n", joined)
print("\nReshaped 3×3 matrix:\n", matrix_3x3)
print("\nDiagonal elements:\n", diagonal)


Joined array:
 [1 2 3 4 5 6 7 8 9]

Reshaped 3×3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements:
 [1 5 9]


10)

In [ ]:
import numpy as np
arr = np.arange(1, 21)
div_by_3_or_5 = arr[(arr % 3 == 0) | (arr % 5 == 0)]

count = div_by_3_or_5.size

print("Original array:\n", arr)
print("\nValues divisible by 3 or 5:\n", div_by_3_or_5)
print("\nCount of such values:", count)


Original array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Values divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]

Count of such values: 9
